// <auto-generated>
// Code generated by LUISGen C:\drop\TechBash.json -cs Luis.TechBash -o C:\drop
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ConferenceBot.Model.Luis
{
    public class TechBashLuisRecognizerResult : Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent
        {
            Evaluation,
            None,
            Registration,
            Schedule
        };
        public Dictionary<Intent, Microsoft.Bot.Builder.Ai.LUIS.IntentData> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] speaker;
            public string[] topic;

            // Built-in entities
            public Microsoft.Bot.Builder.Ai.LUIS.DateTimeSpec[] datetime;

            // Composites
            public class _InstanceSpeakerFullName
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] speaker;
            }
            public class SpeakerFullNameClass
            {
                public string[] speaker;
                [JsonProperty("$instance")]
                public _InstanceSpeakerFullName _instance;
            }
            public SpeakerFullNameClass[] SpeakerFullName;

            // Instance
            public class _Instance
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] speaker;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] topic;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] datetime;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] SpeakerFullName;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties { get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<TechBashLuisRecognizerResult>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score;
                }
            }
            return (maxIntent, max);
        }
    }
}